#!/bin/sh -e

cmake -B build -G Ninja \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_INSTALL_PREFIX=/usr \
         -DCMAKE_VERBOSE_MAKEFILE=ON \
         -DCMAKE_C_FLAGS="$CFLAGS"
cmake --build build
DESTDIR="$1" cmake --install build
