#!/bin/sh -e

patch -p1 < libressl.patch

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --rundir=/run \
    --libexecdir=/usr/lib/dhcpcd \
    --without-udev

make
make DESTDIR="$1" BINMODE=755 install
