#!/bin/sh -e

cat << EOF
This repository is being maintained as an experiment to the BUS factor.
If people fear and run to openssl then we explore the other path.
If the experiment turns out to be successful, this might ressurect old
remote. https://github.com/kiss-community/repo
EOF
