#!/bin/sh -e

prefix=${KISS_ROCM_PREFIX:-/usr/lib/rocm}
export ROCM_PATH="$prefix" HIP_PATH="$prefix" HIP_PLATFORM=amd
export HIP_CLANG_PATH="$prefix/llvm/bin"
export PATH="$prefix/llvm/bin:$prefix/bin:$PATH"
patch -p1 < optional-fortran.patch
cmake -B build -G Ninja \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$prefix" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_PREFIX_PATH="$prefix;$prefix/llvm" \
    -DCMAKE_INSTALL_RPATH="$prefix/lib;$prefix/llvm/lib" \
    -DCMAKE_CXX_COMPILER="$prefix/llvm/bin/clang++" \
    -DROCM_PATH="$prefix" \
    -DBUILD_WITH_SOLVER=OFF \
    -DBUILD_FORTRAN_CLIENTS=OFF \
    -DBUILD_CLIENTS_TESTS=OFF \
    -DBUILD_CLIENTS_SAMPLES=OFF \
    -DBUILD_CLIENTS_BENCHMARKS=OFF
cmake --build build
DESTDIR="$1" cmake --install build
