#!/bin/sh -e

# Avoid a build-time Cython dependency; Tensile works with the pure Python implementation.
export MSGPACK_PUREPYTHON=1

gpep517 build-wheel --wheel-dir .dist --output-fd 3 3>&1 >&2
python -m installer -d "$1" .dist/*.whl
