#!/bin/sh -e

export LIBS="-lcrypto -lz"
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-ipv6 \
    --disable-debug

make
make DESTDIR="$1" PREFIX=/usr install
