#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin

make
install -Dm755 sapi/cli/php "$1/usr/bin/php"
install -Dm755 sapi/cli/php.1 "$1/usr/share/man/man1/php.1"
install -Dm755 sapi/cgi/php-cgi "$1/usr/bin/php-cgi"
install -Dm755 sapi/cgi/php-cgi.1 "$1/usr/share/man/man1/php-cgi.1"
install -Dm755 sapi/phpdbg/phpdbg "$1/usr/bin/phpdbg"
install -Dm755 sapi/phpdbg/phpdbg.1 "$1/usr/share/man/man1/phpdbg.1"
mkdir -p "$1/usr/include/php/"
cp ext/standard/*.h "$1/usr/include/php/"
