#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib/qemu \
    --enable-linux-user \
    --disable-system \
    --disable-kvm \
    --disable-png \
    --disable-tools \
    --static

make
make DESTDIR="$1" PREFIX=/usr install

for bin in "$1/usr/bin/qemu-"*; do
    mv -f "$bin" "$bin-static"
done

make clean

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib/qemu \
    --disable-tcg-interpreter \
    --disable-debug-info \
    --audio-drv-list=alsa \
    --enable-alsa \
    --enable-bzip2 \
    --enable-curl \
    --enable-curses \
    --disable-docs \
    --disable-fuse \
    --disable-gcrypt \
    --disable-gnutls \
    --disable-gtk \
    --enable-kvm \
    --enable-libudev \
    --enable-libusb \
    --disable-linux-aio \
    --enable-linux-io-uring \
    --disable-nettle \
    --enable-opengl \
    --enable-png \
    --enable-sdl \
    --disable-sdl-image \
    --enable-slirp \
    --enable-virglrenderer \
    --disable-vnc \
    --disable-werror \
    --enable-xkbcommon \
    --enable-zstd \
    --enable-system \
    --disable-user \
    --disable-linux-user \
    --enable-pie

make
make DESTDIR="$1" PREFIX=/usr install
