#!/bin/sh -e

patch -p1 < fix-load_for_all_cards.patch

# Fix a missing include
sed -i '/<dirent.h>/a #include <linux/limits.h>' src/ucm/ucm_exec.c

./configure \
    --without-debug \
    --prefix=/usr

make
make DESTDIR="$1" install
