#!/bin/sh -e

prefix=${KISS_ROCM_PREFIX:-/usr/lib/rocm}
export ROCM_PATH="$prefix" HIP_PATH="$prefix" HIP_PLATFORM=amd
export HIP_CLANG_PATH="$prefix/llvm/bin"
export PATH="$prefix/llvm/bin:$prefix/bin:$PATH"
cmake -B build -G Ninja \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$prefix" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_PREFIX_PATH="$prefix;$prefix/llvm" \
    -DCMAKE_INSTALL_RPATH="$prefix/lib;$prefix/llvm/lib" \
    -DBUILD_TYPE=Release
cmake --build build
DESTDIR="$1" cmake --install build
