#!/bin/sh -e

export DESTDIR="$1"

# Swap to shell script instead of perl script
# for conversion of rules files. See files/xml2lst.
sed 's/xml2lst\.pl/xml2lst/' rules/meson.build > _
mv -f _ rules/meson.build

# Remove po/ dir, and useless i18n module.
sed -e "/subdir('po')/d" -e "/i18n/d" meson.build > _
mv -f _ meson.build

meson setup \
    -Dprefix=/usr \
    -Dmandir=usr/share/man \
    -Dcompat-rules=true \
    -Ddatadir=share \
    output

ninja -C output
ninja -C output install
