#!/bin/sh -e

patch -p1 < vulkan-cache-physical-devices.patch

export DESTDIR="$1"

cmake -B build \
        -DGGML_VULKAN=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX='/usr'

cmake --build build
cmake --install build

