#!/bin/sh -e

mkdir -p ./build-aux
autoreconf -i

./configure \
        --enable-silent-rules \
        --disable-documentation \
        --disable-warnings \
        --with-lex \
        --with-yacc

cd src
make
make DESTDIR="$1" install
