#!/bin/sh -e

export DESTDIR="$1"


# Build autoconf 2.13 for browser's sole use.
(
    cd autoconf2.13

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13

    make
    make install
)

if ! command -v yasm; then (
    cd yasm

    ./configure \
        --prefix=/

    make
    make DESTDIR="$PWD/../junk" install
); fi

for f in zip unzip; do
    if ! kiss list "$f"; then (
        cd "$f"

        make \
            CC="$CC $CFLAGS $CXXFLAGS" \
            -f unix/Makefile generic

        make \
            prefix="$PWD/../junk" \
            -f unix/Makefile install
    ); fi
done

git clone --depth=1 --recursive https://repo.palemoon.org/MoonchildProductions/Pale-Moon.git

export PATH="$PWD/junk/bin:$PATH"

sed -e 's#%SRCDIR%#'"$(realpath .)"'#g' -e "s#%CFLAGS%#$CFLAGS#g" mozconfig.in > ./Pale-Moon/.mozconfig

cd ./Pale-Moon
for patch in ../*.patch; do
    patch -p1 < "$patch"
done

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/browser"

./mach build
./mach stage

mkdir -p "$1/usr/bin"
mkdir -p "$1/usr/lib"

cp -r ../objdir/dist/palemoon "$1/usr/lib/browser"
ln -s ../lib/browser/palemoon "$1/usr/bin/browser"
