#!/bin/sh -e

export DESTDIR="$1"

# Disable tests.
: > test/meson.build

# Make meson_options.txt muon compatible.
sed -E "/boolean/s/'(true|false)'/\1/" meson_options.txt > _
mv -f _ meson_options.txt

meson setup \
    -Dwarning_level=0 \
    -Dprefix='/usr' \
    -Dlocalstatedir='/var' \
    -Dsystemd_logind=false \
    -Dglx=true \
    -Ddri1=true \
    -Ddri2=true \
    -Ddri3=true \
    -Dglamor=true \
    -Dxorg=true \
    -Dxephyr=false \
    -Dxdmcp=true \
    -Ddefault_font_path=/usr/share/fonts \
    output

ninja -C output
ninja -C output install
