#!/bin/sh -e

export DESTDIR="$1"

sed '/DEFAULT_OGL/ s/libGL.so.1/libGLESv2.so.2/' src/video/SDL_egl.c > _
mv _ src/video/SDL_egl.c

cmake -B build \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib

cmake --build   build
cmake --install build
