#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib \
	-DSDL2COMPAT_TESTS=OFF

cmake --build   build
cmake --install build
