#!/bin/sh -e

patch -p1 < alsactl-fix-load-state.patch
patch -p1 < alsactl-fix-nested-iteration.patch

# Fix a missing include
sed -i '/<syslog.h>/a #include <limits.h>' alsactl/utils.c

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-udev-rules-dir=/usr/lib/udev/rules.d \
    --disable-alsaconf \
    --disable-bat \
    --disable-xmlto \
    --disable-nls

make
make DESTDIR="$1" install
